// Colleges Data
export const collegesData = [
  {
    id: 1,
    name: "Indian Institute of Technology Bombay",
    location: "Mumbai, India",
    fees: "₹2.2L",
    logo: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=60&h=60&fit=crop",
    ranking: "NIRF Rank 3",
    students: "10,000+",
    established: "1958",
    programs: "60+",
    acceptanceRate: "2%",
    type: "Engineering",
  },
  {
    id: 2,
    name: "Indian Institute of Science",
    location: "Bangalore, India",
    fees: "₹1.8L",
    logo: "https://images.unsplash.com/photo-1593642532455-2e6e9d2c6d7a?w=60&h=60&fit=crop",
    ranking: "NIRF Rank 1",
    students: "4,000+",
    established: "1909",
    programs: "40+",
    acceptanceRate: "1.5%",
    type: "Science",
  },
  {
    id: 3,
    name: "All India Institute of Medical Sciences",
    location: "New Delhi, India",
    fees: "₹0.1L",
    logo: "https://images.unsplash.com/photo-1576091160399-1123a8340d3f?w=60&h=60&fit=crop",
    ranking: "NIRF Rank 1",
    students: "2,500+",
    established: "1956",
    programs: "30+",
    acceptanceRate: "0.5%",
    type: "Medical",
  },
  {
    id: 4,
    name: "Indian Institute of Management Ahmedabad",
    location: "Ahmedabad, India",
    fees: "₹23L",
    logo: "https://images.unsplash.com/photo-1593642532973-d31b97d0c447?w=60&h=60&fit=crop",
    ranking: "NIRF Rank 1",
    students: "1,200+",
    established: "1961",
    programs: "10+",
    acceptanceRate: "1%",
    type: "Management",
  },
  {
    id: 5,
    name: "National Institute of Design",
    location: "Ahmedabad, India",
    fees: "₹2.5L",
    logo: "https://images.unsplash.com/photo-1552664688-9b4d2b7b9e3e?w=60&h=60&fit=crop",
    ranking: "NIRF Rank 2",
    students: "800+",
    established: "1961",
    programs: "20+",
    acceptanceRate: "5%",
    type: "Design",
  },
  {
    id: 6,
    name: "National Law School of India University",
    location: "Bangalore, India",
    fees: "₹3L",
    logo: "https://images.unsplash.com/photo-1589998059171-9b2b7a4b8d7b?w=60&h=60&fit=crop",
    ranking: "NIRF Rank 1",
    students: "600+",
    established: "1986",
    programs: "15+",
    acceptanceRate: "3%",
    type: "Law",
  },
  {
    id: 7,
    name: "Birla Institute of Technology and Science",
    location: "Pilani, India",
    fees: "₹4.5L",
    logo: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=60&h=60&fit=crop",
    ranking: "NIRF Rank 5",
    students: "13,000+",
    established: "1964",
    programs: "50+",
    acceptanceRate: "2.5%",
    type: "Engineering",
  },
  {
    id: 8,
    name: "St. Stephen's College",
    location: "Delhi, India",
    fees: "₹0.5L",
    logo: "https://images.unsplash.com/photo-1564981797816-1aa1a1d7915b?w=60&h=60&fit=crop",
    ranking: "NIRF Rank 2",
    students: "1,500+",
    established: "1881",
    programs: "25+",
    acceptanceRate: "4%",
    type: "Arts",
  },
  {
    id: 9,
    name: "Indian Institute of Technology Delhi",
    location: "New Delhi, India",
    fees: "₹2.3L",
    logo: "https://images.unsplash.com/photo-1593642532400-2682810df593?w=60&h=60&fit=crop",
    ranking: "NIRF Rank 2",
    students: "8,000+",
    established: "1961",
    programs: "55+",
    acceptanceRate: "1.8%",
    type: "Engineering",
  },
];

// Filter options for colleges
export const collegeFilters = [
  "All Colleges",
  "Engineering",
  "Science",
  "Medical",
  "Management",
  "Design",
  "Law",
  "Arts",
];

// College types for additional filtering
export const collegeTypes = [
  "All Types",
  "Public",
  "Private",
  "Deemed",
];

// Ranking levels
export const rankingLevels = [
  "All Rankings",
  "NIRF Rank 1-5",
  "NIRF Rank 6-10",
  "NIRF Rank 11-20",
  "NIRF Rank 21+",
];