// Jobs Data
// export const jobsData = [
//   {
//     id: 1,
//     title: "Frontend Developer",
//     company: "TechCorp Solutions",
//     location: "Bangalore, India",
//     salary: "₹8-12L",
//     salaryType: "per annum",
//     type: "Full-time",
//     experience: "2-4 years",
//     companyLogo:
//       "https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=60&h=60&fit=crop",
//     postedDate: "2 days ago",
//     applicants: "45+",
//     department: "Engineering",
//     remote: true,
//     skills: ["React", "JavaScript", "TypeScript", "CSS", "HTML"],
//     category: "Technology",
//   },
//   {
//     id: 2,
//     title: "Data Scientist",
//     company: "Analytics Pro",
//     location: "Mumbai, India",
//     salary: "₹12-18L",
//     salaryType: "per annum",
//     type: "Full-time",
//     experience: "3-5 years",
//     companyLogo:
//       "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=60&h=60&fit=crop",
//     postedDate: "1 week ago",
//     applicants: "78+",
//     department: "Data",
//     remote: false,
//     skills: ["Python", "Machine Learning", "SQL", "Tableau", "Statistics"],
//     category: "Data Science",
//   },
//   {
//     id: 3,
//     title: "Digital Marketing Manager",
//     company: "Creative Media",
//     location: "Delhi, India",
//     salary: "₹6-10L",
//     salaryType: "per annum",
//     type: "Full-time",
//     experience: "3-6 years",
//     companyLogo:
//       "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=60&h=60&fit=crop",
//     postedDate: "3 days ago",
//     applicants: "23+",
//     department: "Marketing",
//     remote: true,
//     skills: ["SEO", "Social Media", "Google Ads", "Analytics", "Content"],
//     category: "Marketing",
//   },
//   {
//     id: 4,
//     title: "Backend Developer",
//     company: "ServerTech Inc",
//     location: "Hyderabad, India",
//     salary: "₹10-15L",
//     salaryType: "per annum",
//     type: "Full-time",
//     experience: "2-5 years",
//     companyLogo:
//       "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=60&h=60&fit=crop",
//     postedDate: "5 days ago",
//     applicants: "67+",
//     department: "Engineering",
//     remote: true,
//     skills: ["Node.js", "MongoDB", "Express", "AWS", "Docker"],
//     category: "Technology",
//   },
//   {
//     id: 5,
//     title: "UI/UX Designer",
//     company: "Design Studio",
//     location: "Pune, India",
//     salary: "₹5-8L",
//     salaryType: "per annum",
//     type: "Full-time",
//     experience: "1-3 years",
//     companyLogo:
//       "https://images.unsplash.com/photo-1558655146-d09347e92766?w=60&h=60&fit=crop",
//     postedDate: "1 day ago",
//     applicants: "34+",
//     department: "Design",
//     remote: false,
//     skills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"],
//     category: "Design",
//   },
//   {
//     id: 6,
//     title: "DevOps Engineer",
//     company: "CloudTech Systems",
//     location: "Chennai, India",
//     salary: "₹12-20L",
//     salaryType: "per annum",
//     type: "Full-time",
//     experience: "4-7 years",
//     companyLogo:
//       "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=60&h=60&fit=crop",
//     postedDate: "4 days ago",
//     applicants: "89+",
//     department: "Operations",
//     remote: true,
//     skills: ["Kubernetes", "Docker", "AWS", "Jenkins", "Terraform"],
//     category: "Technology",
//   },
//   {
//     id: 7,
//     title: "Product Manager",
//     company: "StartupXYZ",
//     location: "Bangalore, India",
//     salary: "₹15-25L",
//     salaryType: "per annum",
//     type: "Full-time",
//     experience: "5-8 years",
//     companyLogo:
//       "https://images.unsplash.com/photo-1553484771-371a605b060b?w=60&h=60&fit=crop",
//     postedDate: "6 days ago",
//     applicants: "156+",
//     department: "Product",
//     remote: true,
//     skills: ["Strategy", "Analytics", "Leadership", "Agile", "SQL"],
//     category: "Management",
//   },
//   {
//     id: 8,
//     title: "Content Writer",
//     company: "Media House",
//     location: "Kolkata, India",
//     salary: "₹3-6L",
//     salaryType: "per annum",
//     type: "Part-time",
//     experience: "1-2 years",
//     companyLogo:
//       "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=60&h=60&fit=crop",
//     postedDate: "2 days ago",
//     applicants: "12+",
//     department: "Content",
//     remote: true,
//     skills: ["Writing", "SEO", "Research", "WordPress", "Social Media"],
//     category: "Content",
//   },
//   {
//     id: 9,
//     title: "Software Tester",
//     company: "QualityFirst",
//     location: "Noida, India",
//     salary: "₹4-7L",
//     salaryType: "per annum",
//     type: "Full-time",
//     experience: "1-3 years",
//     companyLogo:
//       "https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=60&h=60&fit=crop",
//     postedDate: "1 week ago",
//     applicants: "28+",
//     department: "QA",
//     remote: false,
//     skills: ["Selenium", "Manual Testing", "API Testing", "JIRA", "Postman"],
//     category: "Technology",
//   },
// ];

export const jobsData = [
  {
    id: 1,
    title: "Senior UI Developer",
    company: "Nike",
    companyLogo:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=50&h=50&fit=crop",
    salary: "$120/hr",
    location: "San Francisco, CA",
    type: "Remote",
    posted: "2 days ago",
    bgColor: "bg-purple-100",
  },
  {
    id: 2,
    title: "Senior Backend Engineer",
    company: "Google",
    companyLogo:
      "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=50&h=50&fit=crop",
    salary: "$150/hr",
    location: "Mountain View, CA",
    type: "Full-time",
    posted: "1 day ago",
    bgColor: "bg-blue-100",
  },
  {
    id: 3,
    title: "Azure Data Engineer",
    company: "Airbnb",
    companyLogo:
      "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=50&h=50&fit=crop",
    salary: "$125-145/hr",
    location: "Seattle, WA",
    type: "Contract",
    posted: "3 days ago",
    bgColor: "bg-green-100",
  },
  {
    id: 4,
    title: "Frontend Developer",
    company: "Microsoft",
    companyLogo:
      "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=50&h=50&fit=crop",
    salary: "$125-145/hr",
    location: "Austin, TX",
    type: "Hybrid",
    posted: "1 week ago",
    bgColor: "bg-yellow-100",
  },
  {
    id: 5,
    title: "Senior Backend Engineer",
    company: "Meta",
    companyLogo:
      "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=50&h=50&fit=crop",
    salary: "$150/hr",
    location: "New York, NY",
    type: "Remote",
    posted: "4 days ago",
    bgColor: "bg-pink-100",
  },
  {
    id: 6,
    title: "Senior UI Developer",
    company: "Apple",
    companyLogo:
      "https://images.unsplash.com/photo-1621768216002-5ac171876625?w=50&h=50&fit=crop",
    salary: "$120/hr",
    location: "Cupertino, CA",
    type: "Full-time",
    posted: "5 days ago",
    bgColor: "bg-indigo-100",
  },
];

// Filter options for jobs
export const jobFilters = [
  "All Jobs",
  "Technology",
  "Design",
  "Marketing",
  "Data Science",
  "Management",
  "Content",
];

// Job types for additional filtering
export const jobTypes = [
  "All Types",
  "Full-time",
  "Part-time",
  "Contract",
  "Internship",
];

// Experience levels
export const experienceLevels = [
  "All Levels",
  "0-1 years",
  "1-3 years",
  "3-5 years",
  "5+ years",
];
